FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install the xz-utils package
RUN apt-get update && apt-get -y install gcc-arm-none-eabi && apt-get -y install gdb-multiarch && apt-get -y install telnet
